[programs.localnet]
solana_twitter = "AyCdgphakGxHDBgqEPNw2wf7NjHhfVwfAjfpmu5vfc4Q"

[programs.devnet]
solana_twitter = "AyCdgphakGxHDBgqEPNw2wf7NjHhfVwfAjfpmu5vfc4Q"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy = "cp target/idl/solana_twitter.json app/src/idl/localnet.json"
copy-devnet = "cp target/idl/solana_twitter.json app/src/idl/devnet.json"
copy-mainnet = "cp target/idl/solana_twitter.json app/src/idl/mainnet.json"
